### ISSUE TITLE
The old grommet-control page is deprecated

### ISSUE THREAD

**Issue by abbasmeeran** [atanasster/grommet-controls-sample#5]
I have been trying to use grommet-controls with the latest grommet.
the grommet-controls was in broken state.
grommet-nextjs.herokuapp.com

I see latest commits and new sample app for grommet-controls.

Can I start using grommet-controls with latest grommet.

Will this repository be actively maintained for any issues?

**Comment by atanasster** [comment]
Hi,
The docs page is at https://grommet-controls.netlify.app/. I am maintaining this one as i use it as a test bed for component-controls.com

As for grommet-controls the library - i am not using grommet for a while now and do not plan to significantly maintain it myself. I will accept and merge PRs, and if someone can Commit  to become a maintainer J would welcome that.
